site_name: Dexplo
site_description: Documentation for the full suite of Dexplo Python data analysis libraries
site_author: Ted Petrou
site_url: https://www.dexplo.org
repo_url: https://github.com/dexplo
copyright: Copyright @ 2020 Ted Petrou

google_analytics: ['UA-119777567-7', 'dexplo.org']

theme: 
    name: material
    features:
        - tabs
    
nav:
    - Home: 'index.md'

extra:
  social:
    - icon: fontawesome/brands/github-alt
      link: https://github.com/dexplo
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/TedPetrou
    - icon: fontawesome/brands/linkedin
      link: https://linkedin.com/in/TedPetrou
    - icon: fontawesome/brands/youtube
      link: https://www.youtube.com/c/dunderdata

markdown_extensions:
    - admonition
    - toc:
        permalink: True
    - codehilite:
        guess_lang: false

plugins:
    - search
    - minify:
        minify_html: true

extra_javascript:
  - https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.0/MathJax.js?config=TeX-MML-AM_CHTML